/*
 * Copyright 2019 Thorsis Technologies GmbH
 */

#ifndef PROFICUBE_FPGA
#define PROFICUBE_FPGA

#define PROFICUBE_FPGA_PIN_nCONFIG	AT91_PIO_PORTA, 8
#define PROFICUBE_FPGA_PIN_CONF_DONE	AT91_PIO_PORTA, 9
#define PROFICUBE_FPGA_PIN_nSTATUS	AT91_PIO_PORTA, 10
#define PROFICUBE_FPGA_PIN_DCLK		AT91_PIO_PORTA, 14
#define PROFICUBE_FPGA_PIN_DATA0	AT91_PIO_PORTA, 15

#define PROFICUBE_USE_SPI		1

#define PROFICUBE_FPGA_SPI_BUS		0
#define PROFICUBE_FPGA_SPI_CS		1 /* just to please the SPI controller */
#define PROFICUBE_FPGA_SPI_DEV_NAME	"fpga@1"
#define PROFICUBE_FPGA_SPI_SPEED	50000000 /* from 83 MHz / 255 = 325490 Hz to 83 MHz */

void board_fpga_init(void);

#endif
