#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Stelian Pop <stelian.pop@leadtechdesign.com>
# Lead Tech Design <www.leadtechdesign.com>
#
# Copyright 2010,2012 ifak system GmbH
# Copyright 2019 Thorsis Technologies GmbH
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y				+= at91sam9g20ncl.o
obj-$(CONFIG_AT91_LED)		+= led.o
obj-$(CONFIG_TT_NCL_BUTTON)	+= button.o
obj-$(CONFIG_FPGA)		+= fpga.o
obj-y				+= backplane.o
obj-y				+= hrttest.o

# vim: ft=make noet sts=0 ts=8 sw=8 sr
