# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Stelian Pop <stelian.pop@leadtechdesign.com>
# Lead Tech Design <www.leadtechdesign.com>
#
# (C) Copyright 2010
# ifak system GmbH
#
# (C) Copyright 2019
# Thorsis Technologies GmbH

obj-y				+= isnet_lite.o
obj-$(CONFIG_LED)		+= isnet_lite_led.o
obj-$(CONFIG_FPGA)		+= fpga.o
obj-y				+= backplane.o
obj-y				+= hrttest.o

# vim: ft=make noet sts=0 ts=8 sw=8 sr
